#!/usr/bin/env bash
# This script prints the information about a domain/subdomain

# grep -A1 finds the pattern specified and included one line below it
#+ tail -n 1 grabs the line below the pattern specified in grep
#+ -E flag signifies extended regexp. It looks for a pattern e.g "www."
#+ and replaces it with "www"
#+ -F flag in awk specifies the delimiter, space in this case
print_domain_record ()
{
	dig "$1" | grep -A1 "ANSWER SECTION:" | tail -n 1 | sed -E "s/$1./$2/" | awk -F' ' '{print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}

if [[ "$#" -eq 2 ]]
then
	print_domain_record "$2.$1" "$2"
else
	print_domain_record "www.$1" "www"
	print_domain_record "lb-01.$1" "lb-01"
	print_domain_record "web-01.$1" "web-01"
	print_domain_record "web-02.$1" "web-02"
fi
echo " "
dig "$1" | grep -A1 "ANSWER SECTION:" | tail -n 1 | sed -E "s/$1./$2/p"
