#!/usr/bin/env bash
# This script installs nginx on a linux ubuntu distro
#+ and returns hello world when the web server is queried

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
