#!/usr/bin/env bash
# This script installs nginx on a linux ubuntu distro
#+ and configures a permanent redirection

redir="^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "47i rewrite $redir" /etc/nginx/sites-available/default
sudo service nginx restart
