#!/usr/bin/env bash
# This script installs nginx on a linux ubuntu distro
#+ and configures a permanent redirection

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent' /etc/nginx/sites-available/default
service nginx restart
