#!/usr/bin/env bash
# This script installs nginx on a linux ubuntu distro
#+ and configures a permanent redirection

sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/server_name/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
