#!/usr/bin/env bash
# This script installs nginx on a linux ubuntu distro
#+ and configures a custom 404 page

redir="^/redirect https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "47i rewrite $redir" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "47i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
