#!/usr/bin/env bash
# This script configures a HAProxy load balancer that uses a
#+ round robin algorithm

frontend_and_backend="\
frontend myfrontend
        mode http
        bind *:80
        default_backend nginx_web_servers

backend nginx_web_servers
        mode http
        balance roundrobin
        server 136616-web-01 18.235.234.96:80 check
        server 136616-web-02 52.87.216.23:80 check
"
# Installation
sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get install -y haproxy=2.7.\*

# Enable management of HAProxy with init script
echo "# Set ENABLED to 1 if you want the init script to start haproxy" | sudo tee -a /etc/default/haproxy > /dev/null
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null


# configure backend section of haproxy.cfg for load balancing
echo "$frontend_and_backend" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# restart the load balancer service
sudo service haproxy restart
