#!/usr/bin/env bash
# This script creates an archive file of the MySQL dump file

# create the dump file
mysqldump -uroot -p"$1" --all-databases --events > backup.sql

# Get the current date
curr_date=$(date '+%d-%m-%Y')

# compress the dump file to a tar.gz archive
tar -cvzf "$curr_date.tar.gz" backup.sql
