#!/usr/bin/env bash
# This script configures a nginx server to listen on port 80

# Enter the sites-enabled directory or exit if it does not exist
cd /etc/nginx/sites-enabled || exit;

# Since the `default` file listens on port 8080, and it's a symlink
#+ to /etc/nginx/sites-available/default, delete it
sudo rm default || exit;

# create a new link
sudo ln -s /etc/nginx/sites-available/default default;

# restart nginx
sudo service nginx restart
