#!/usr/bin/env bash
# This script configures a nginx server to listen on port 80
sudo sed -i "s/listen 8080 default_server;/listen 80 default_server;/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server ipv6only=on;/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
