#!/usr/bin/env bash
# This script creates a file in /var/run directory,
#+ Displays a string infinitely, traps SIGTERM & SIGINT signals and
#+ displays appropriate messages. It deletes the created file if it 
#+ receives SIGQUIT or SIGTERM signal and terminates program

trap "echo Y U no love me?!;" SIGINT
trap "echo I hate the kill command && rm /var/run/myscript.pid; exit" SIGQUIT SIGTERM

echo $$ > /var/run/myscript.pid

while true;
do
	printf "To infinity and beyond\n"
	sleep 2
done
