#!/usr/bin/env bash
# This script manages `manage_my_process` script
#+ like an init script

if [[ $1 == "start" ]]
then
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	printf "manage_my_process started\n"

elif [[ $1 == "stop" ]]
then
	# The pid of the background process is stored in /var/run/my_process.pid
	#+ This is used to stop the process
	pid=$(cat /var/run/my_process.pid)
	kill "$pid"
	rm /var/run/my_process.pid
	printf "manage_my_process stopped\n"

elif [[ $1 == "restart" ]]
then
	pid=$(cat /var/run/my_process.pid)
	kill "$pid"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	printf "manage_my_process restarted\n"
else
	printf "Usage: manage_my_process {start|stop|restart}\n"
fi
