#!/usr/bin/env bash
# This scripts writes a string to a file indefinitely

while true;
do
	# Error messages are not shown; pushed to the void
	echo I am alive >> /tmp/my_process 2> /dev/null
	sleep 2
done
