#!/usr/bin/env bash
# This script implements the `FizzBuzz` test


for (( num=1; num<=100; num++));
do
	if [[ $((num % 3)) -eq 0 && $((num % 5)) -eq 0 ]]
	then
		printf "FizzBuzz\n"
	elif [[ $((num % 3)) -eq 0 ]]
	then
		printf "Fizz\n"

	elif [[ $((num % 5)) -eq 0 ]]
	then
		printf "Buzz\n"
	else
		printf "%d\n" "$num"

	fi
done
