#!/usr/bin/env bash
# This script displays the content of /etc/passwd file
#+ formatted to give username, user id, and Home directory
#+ for path user. The delimiter is ":"

while read -r line;
do
	var1=$(echo "$line" | cut -d ':' -f 1,3,6 --output-delimiter=':')
	printf "%s\n" "$var1"
done < /etc/passwd
