#!/usr/bin/env bash
# This script parses downloaded Apache web server log files
#+ and groups the output by Number of occrences, IP addresses,
#+ and HTTP status codes

cat < apache-access.log | awk '{print $1,$9}' | sort | uniq -c | sort -rn
