#!/usr/bin/env bash
# This script displays "Best School" 10 times using 
#+ while loop. Prints an additonal string on the 9th iteration

i=1

while [[ $i -le 10 ]];
do
	if [[ $i -eq 4 ]]
	then
		printf "bad luck\n"

	elif [[ $i -eq 8 ]]
	then
		printf "good luck\n"

	else
		printf "Best School\n"
	fi

	((i++))
done
