#!/usr/bin/env bash
# This script displays integers from 1-20, with
#+ case statements to print formatted outputs

i=1

while [[ $i -le 20 ]];
do
	case $i in
		4)
			printf "%d\nbad luck from China\n" "$i"
			;;
		9)
			printf "%d\nbad luck from Japan\n" "$i"
			;;
		17)
			printf "%d\nbad luck from Italy\n" "$i"
			;;
		*)
			printf "%d\n" "$i"
			;;
		esac
	((i++))
done
