#!/usr/bin/env bash
# This script changes the IP addresses of hostnames:
#+ localhost & facebook.com

facebookip=8.8.8.8
facebookhost="facebook.com"
localhost="localhost"
newlocalip='127.0.0.2'

FACEBOOKLINE="$facebookip	$facebookhost"

# Copy original /etc/hosts to file to modify on docker container
#+ Docker overwrites /etc/hosts without regard for your modifications
cp /etc/hosts ~/hosts.new

# Check if host exists
grep -q $facebookhost ~/hosts.new

# If hosts exists, `$?` returns 0
res=$?
if [[ $res = 0 ]]
then
	# Resolve the new ip
	sed -i "/$facebookhost/ s/.*/$facebookip\t$facebookhost/" ~/hosts.new
	printf "host exists\n"
else
	# append host & ip address
	echo "$FACEBOOKLINE" >> ~/hosts.new
fi

# Set localhost IP
sed -i "s/127.0.0.*/$newlocalip\t$localhost/" ~/hosts.new
#sed -i "/$localhost$/ s/.*/$newlocalip\t$localhost/g" ~/hosts.new

# force copy to /etc/hosts
cp -f ~/hosts.new /etc/hosts
