#!/usr/bin/env bash
# configure nginx to run as user nginx and listen on port 8080
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo chown -R nginx /etc/nginx/nginx.conf
su - nginx -c "sed -i 's/80/8080/g' /etc/nginx/sites-available/default"
su - nginx -c "service nginx restart"
