#!/usr/bin/env bash
# Reloads gunicorn by sending a SIGHUP signal to the master process
# to re-read the config file that may or may not have been changed

# alternative command with grep doesn't pass shellcheck, but will still work
#ps auxf | grep '[g]unicorn' | awk '{print $2}' | xargs | cut -d ' ' -f 1 | xargs kill -HUP
pgrep gunicorn | xargs | cut -d ' ' -f 1 | xargs kill -HUP
